* Install prerequisites
#+BEGIN_SRC shell
$ sudo apt-get install gcc build-essential git emacs
#+END_SRC
* Clone pug
#+BEGIN_SRC shell
$ git clone https://github.com/pugofer/pug.git
#+END_SRC
* Build

Above should make a directory called =pug=\\
Usually in your home but that depends on where you ran the git clone.

Following I'll use the expression =/path/to/pug/...=

Please replace =path/to= by the actual path.

In most cases =~= should be sufficient.

*Except the shell export variable* =PUG= -- see below at end of *Check executable*

cd into =/path/to/pug/src= and run
#+BEGIN_SRC shell
$ make
#+END_SRC

* Check executable

Above should make an executable called pug. When you run it (at shell as:)
#+BEGIN_SRC shell
$ ./pug
#+END_SRC
This should start the interpreter.

Note that this is starting from the ~pug/src~ directory -- not an ideal setup!

To run it from anywhere you need:
1. =pug= executable in your =PATH=
2. =PUG= environment variable setup like so:
#+BEGIN_SRC shell
$ export PUG=/path/to/pug/preludes/pup.pre
#+END_SRC

Warning: As of now ~pug~ does not understand =~=; Use =$HOME= 

The 3 standard preludes you can try are
- =pup= :: Absolutely minimum required to start
- =pug= :: No classes =Eq=, =Num= etc
- =standard= :: the standard prelude
- =cat= :: the constructor class prelude
* Non-emacs Use
If you dont want to use emacs, this much should be sufficient:

Just have ~pug~ running in one window, an editor of your choice in another and whenever you want to load a changed file to ~pug~ do (from within ~pug~)
#+BEGIN_SRC haskell
:l filename.gs
#+END_SRC
For emacs setup you will need to setup from the [[https://github.com/pugofer/emacs-pug][emacs repo]].
